name: nana_alert
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.6
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  intl: ^0.18.1
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter_icons:
#   image_path: "assets/logo/something.png"
#   shadow: true
#   adaptive_icon_background: "#123123"
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   web:
#     generate: true
#     image_path: "assets/logo/something.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/brand/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
