// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjT67yk5tHIfW52D1IgAbWLLZHKts43Y',
    appId: '1:111562529284:web:ee2a6db082eff4fff5b351',
    messagingSenderId: '111562529284',
    projectId: 'nana-alert',
    authDomain: 'nana-alert.firebaseapp.com',
    storageBucket: 'nana-alert.appspot.com',
    measurementId: 'G-L9KYC224C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3pCXUCec4z8gWaIBwpWXo7vgWKhHRrvk',
    appId: '1:111562529284:android:27575c59f7123f1df5b351',
    messagingSenderId: '111562529284',
    projectId: 'nana-alert',
    storageBucket: 'nana-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv0oeXvsOIZAkrwIumQFClpup1bLyTRq8',
    appId: '1:111562529284:ios:aecba3e8b02dca95f5b351',
    messagingSenderId: '111562529284',
    projectId: 'nana-alert',
    storageBucket: 'nana-alert.appspot.com',
    iosBundleId: 'com.example.nanaAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv0oeXvsOIZAkrwIumQFClpup1bLyTRq8',
    appId: '1:111562529284:ios:164dd1bbb7632daef5b351',
    messagingSenderId: '111562529284',
    projectId: 'nana-alert',
    storageBucket: 'nana-alert.appspot.com',
    iosBundleId: 'com.example.nanaAlert.RunnerTests',
  );
}
